/**
 * @file plugin_data_types.h
 * @brief Private types and limits shared by plugin-data modules.
 */

#ifndef PLUGIN_DATA_TYPES_H
#define PLUGIN_DATA_TYPES_H

#include <stddef.h>
#include <windows.h>

#define CATIME_MAIN_WINDOW_CLASS_NAME L"CatimeWindowClass"
#define PLUGIN_DISPLAY_RETAIN_WCHARS 4096
#define PLUGIN_PREVIEW_MAX_EXIT_COUNTDOWN_SECONDS 3600

#define PLUGIN_DATA_REDRAW_TIMER_ID 42424
#define PLUGIN_DATA_REDRAW_MIN_INTERVAL_MS 100
#define PLUGIN_DATA_WATCHER_SHUTDOWN_WAIT_MS 2000
#define PLUGIN_DATA_WATCHER_UI_STOP_WAIT_MS 1000
#define PLUGIN_DATA_WATCHER_STOP_GATE_WAIT_MS 1000
#define PLUGIN_DATA_WATCHER_START_FAILURE_COOLDOWN_MS 2000

#define DEFAULT_POLL_INTERVAL_MS 500
#define MIN_POLL_INTERVAL_MS PLUGIN_DATA_REDRAW_MIN_INTERVAL_MS
#define MAX_POLL_INTERVAL_MS 5000
#define MAX_PLUGIN_OUTPUT_BYTES (10ull * 1024ull * 1024ull)
#define PLUGIN_DISPLAY_MAX_INPUT_BYTES 4096
#define PLUGIN_OUTPUT_READ_LIMIT_BYTES (PLUGIN_DISPLAY_MAX_INPUT_BYTES + 4)
#define PLUGIN_OUTPUT_STACK_BUFFER_BYTES 1024
#define PLUGIN_DISPLAY_STACK_WCHARS 1024
#define PLUGIN_LAST_CONTENT_RETAIN_BYTES (64 * 1024)
#define MAX_CHANGE_DEBOUNCE_MS 50
#define PLUGIN_OUTPUT_FILE_SHARE (FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE)

#define NOTIFY_MIN_INTERVAL_MS 1000
#define PLUGIN_OUTPUT_FILENAME "output.txt"
#define PLUGIN_OUTPUT_FILENAME_W L"output.txt"

typedef struct {
    wchar_t message[1025];
    int type;
    int timeout;
    BOOL pending;
} PendingNotification;

typedef enum {
    PLUGIN_PARSE_FAILED = 0,
    PLUGIN_PARSE_OK,
    PLUGIN_PARSE_TRANSIENT_FAILURE
} PluginParseResult;

#endif /* PLUGIN_DATA_TYPES_H */
