#include "dialog_countdown_part01.inc"
#include "dialog_countdown_part02.inc"
#include "dialog_countdown_part03.inc"
#include "dialog_countdown_part04.inc"
#include "dialog_countdown_part05.inc"
#include "dialog_countdown_part06.inc"
#include "dialog_countdown_part07.inc"
#include "dialog_countdown_part08.inc"
