/**
 * @file config_constants.h
 * @brief Stable configuration defaults, limits, paths, and INI sections.
 */

#ifndef CATIME_CONFIG_CONSTANTS_H
#define CATIME_CONFIG_CONSTANTS_H

#define MAX_RECENT_FILES 5

#define DEFAULT_TIMEOUT_MESSAGE "Ding! Time's up~"
#define NOTIFICATION_USE_FOR_POMODORO_KEY "NOTIFICATION_USE_FOR_POMODORO"
#define NOTIFICATION_MESSAGE_CHAR_BUFFER_SIZE 256
#define NOTIFICATION_MESSAGE_BUFFER_SIZE \
    ((NOTIFICATION_MESSAGE_CHAR_BUFFER_SIZE * 4) + 1)

#define LOCALAPPDATA_PREFIX "%LOCALAPPDATA%\\Catime"
#define FONTS_PATH_PREFIX \
    "%LOCALAPPDATA%\\Catime\\resources\\fonts\\"
#define AUDIO_PATH_PREFIX \
    "%LOCALAPPDATA%\\Catime\\resources\\audio\\"
#define ANIMATIONS_PATH_PREFIX \
    "%LOCALAPPDATA%\\Catime\\resources\\animations\\"

#define DEFAULT_TEXT_COLOR "#FFFFFF_#00FFFF"
#define DEFAULT_WHITE_COLOR "#FFFFFF"
#define DEFAULT_BLACK_COLOR "#000000"
#define DEFAULT_FONT_NAME "Terminess Nerd Font Propo Essence.ttf"
#define DEFAULT_FONT_SIZE 20

#define DEFAULT_WINDOW_SCALE "1.62"
#define DEFAULT_PLUGIN_SCALE "1.0"
#define DEFAULT_WINDOW_POS_X -2
#define DEFAULT_WINDOW_POS_Y -1
#define WINDOW_POSITION_MANUAL_KEY "WINDOW_POSITION_MANUAL"
#define WINDOW_MONITOR_ID_KEY "WINDOW_MONITOR_ID"
#define WINDOW_MONITOR_OFFSET_X_KEY "WINDOW_MONITOR_OFFSET_X"
#define WINDOW_MONITOR_OFFSET_Y_KEY "WINDOW_MONITOR_OFFSET_Y"
#define WINDOW_TASKBAR_ANCHORED_KEY "WINDOW_TASKBAR_ANCHORED"
#define WINDOW_TASKBAR_AXIS_RATIO_KEY "WINDOW_TASKBAR_AXIS_RATIO"
#define WINDOW_TASKBAR_CROSS_OFFSET_KEY "WINDOW_TASKBAR_CROSS_OFFSET"
#define DEFAULT_MOVE_STEP_SMALL 10
#define DEFAULT_MOVE_STEP_LARGE 50
#define DEFAULT_SCALE_STEP_NORMAL 10
#define DEFAULT_SCALE_STEP_FAST 15

#define DEFAULT_COLOR_OPTIONS_INI \
    "#FFFFFF,#E3E3E5,#000000,#FF5F5F,#F6ABB7,#FB7FA4,#F59E0B,#22C55E,#8771C6," \
    "#FF9A9E_#FECFEF,#FEA5B7_#FFDE9B,#A8EDEA_#FED6E3,#D299C2_#FEF9D7," \
    "#FF9966_#FF5E62,#ED4264_#FFEDBC,#F6D365_#FDA085,#FFE985_#FA742B,#FF9A56_#56CCBA," \
    "#10BD92_#8CE442,#11998E_#38EF7D,#43E97B_#38F9D7," \
    "#FFFFFF_#00FFFF,#89F7FE_#66A6FF,#00C9FF_#92FE9D,#648CFF_#64DC78,#1F92A9_#EEE0D5," \
    "#8E9EF3_#F774A0,#FF5E96_#56C6FF,#30CFD0_#330867," \
    "#FFA745_#FE869F_#EF7AC8_#A083ED_#43AEFF"

#define INI_SECTION_GENERAL "General"
#define INI_SECTION_DISPLAY "Display"
#define INI_SECTION_TIMER "Timer"
#define INI_SECTION_POMODORO "Pomodoro"
#define INI_SECTION_NOTIFICATION "Notification"
#define INI_SECTION_HOTKEYS "Hotkeys"
#define INI_SECTION_RECENTFILES "RecentFiles"
#define INI_SECTION_COLORS "Colors"
#define INI_SECTION_OPTIONS "Options"
#define INI_SECTION_PLUGIN_TRUST "PluginTrust"

#define ANIMATION_FIXED_SPEED_MIN_MULTIPLIER 0.1
#define ANIMATION_FIXED_SPEED_MAX_MULTIPLIER 30.0
#define ANIMATION_FIXED_SPEED_DEFAULT_MULTIPLIER 2.0
#define MAX_TRUSTED_PLUGINS 32

#endif /* CATIME_CONFIG_CONSTANTS_H */
