/* 版本与更新信息 */
#define CATIME_VERSION "1.0.4.2"
#define UPDATE_URL_GITHUB    "https://github.com/vladelaina/Catime/releases"
#define UPDATE_URL_123PAN    "https://www.123684.com/s/ruESjv-2CZUA"
#define UPDATE_URL_LANZOU    "https://wwrx.lanzoup.com/b00hqiiskj"
#define FEEDBACK_URL        "https://www.bilibili.com/video/BV1ztFeeQEYP"
#define FEEDBACK_URL_GITHUB  "https://github.com/vladelaina/Catime/issues"
#define FEEDBACK_URL_BILIBILI "https://message.bilibili.com/#/whisper/mid1862395225"


/* 窗口尺寸增长量 */
#define WINDOW_HORIZONTAL_PADDING 190  //左右
#define WINDOW_VERTICAL_PADDING -5     //上下

/* 系统按键定义 */
#define VK_MEDIA_PLAY_PAUSE 0xB3
#define VK_MEDIA_STOP 0xB2
#define KEYEVENTF_KEYUP 0x0002

/* 主对话框与核心控件 */
#define IDI_CATIME 101
#define CLOCK_ID_TRAY_APP_ICON 1001
#define CLOCK_IDD_DIALOG1 1002
#define CLOCK_IDD_COLOR_DIALOG 1003
#define CLOCK_IDC_EDIT 108
#define CLOCK_IDC_BUTTON_OK 109
#define CLOCK_IDC_CUSTOMIZE_LEFT 112
#define CLOCK_IDC_EDIT_MODE 113
#define CLOCK_IDC_MODIFY_OPTIONS 114
#define CLOCK_IDC_STATIC 1001

/* 字体配置 */
// 字体菜单项
#define CLOCK_IDC_FONT_MENU 113
#define CLOCK_IDC_FONT_RECMONO 342
#define CLOCK_IDC_FONT_DEPARTURE 320
#define CLOCK_IDC_FONT_TERMINESS 343
#define CLOCK_IDC_FONT_GOHUFONT 346
#define CLOCK_IDC_FONT_YESTERYEAR 390
#define CLOCK_IDC_FONT_ZCOOL_KUAILE 391
#define CLOCK_IDC_FONT_PROFONT 392
#define CLOCK_IDC_FONT_DADDYTIME 393

// 新增字体菜单项
#define CLOCK_IDC_FONT_ARBUTUS 347
#define CLOCK_IDC_FONT_BERKSHIRE 348
#define CLOCK_IDC_FONT_CAVEAT 349
#define CLOCK_IDC_FONT_CREEPSTER 350
#define CLOCK_IDC_FONT_DOTGOTHIC 351
#define CLOCK_IDC_FONT_DOTO 352
#define CLOCK_IDC_FONT_FOLDIT 354
#define CLOCK_IDC_FONT_FREDERICKA 355
#define CLOCK_IDC_FONT_FRIJOLE 356
#define CLOCK_IDC_FONT_GWENDOLYN 358
#define CLOCK_IDC_FONT_HANDJET 359
#define CLOCK_IDC_FONT_INKNUT 360
#define CLOCK_IDC_FONT_JACQUARD 361
#define CLOCK_IDC_FONT_JACQUARDA 362
#define CLOCK_IDC_FONT_KAVOON 363
#define CLOCK_IDC_FONT_KUMAR_ONE_OUTLINE 364
#define CLOCK_IDC_FONT_KUMAR_ONE 365
#define CLOCK_IDC_FONT_LAKKI_REDDY 366
#define CLOCK_IDC_FONT_LICORICE 367
#define CLOCK_IDC_FONT_MA_SHAN_ZHENG 368
#define CLOCK_IDC_FONT_MOIRAI_ONE 369
#define CLOCK_IDC_FONT_MYSTERY_QUEST 370
#define CLOCK_IDC_FONT_NOTO_NASTALIQ 371
#define CLOCK_IDC_FONT_PIEDRA 372
#define CLOCK_IDC_FONT_PIXELIFY 373
#define CLOCK_IDC_FONT_PRESS_START 374
#define CLOCK_IDC_FONT_RUBIK_BUBBLES 376
#define CLOCK_IDC_FONT_RUBIK_BURNED 377
#define CLOCK_IDC_FONT_RUBIK_GLITCH_POP 378
#define CLOCK_IDC_FONT_RUBIK_GLITCH 379
#define CLOCK_IDC_FONT_RUBIK_MARKER_HATCH 380
#define CLOCK_IDC_FONT_RUBIK_PUDDLES 381
#define CLOCK_IDC_FONT_RUBIK_VINYL 382
#define CLOCK_IDC_FONT_RUBIK_WET_PAINT 383
#define CLOCK_IDC_FONT_RUGE_BOOGIE 384
#define CLOCK_IDC_FONT_SEVILLANA 385
#define CLOCK_IDC_FONT_SILKSCREEN 386
#define CLOCK_IDC_FONT_STICK 387
#define CLOCK_IDC_FONT_UNDERDOG 388
#define CLOCK_IDC_FONT_WALLPOET 389

// 字体资源ID
#define IDR_FONT_RECMONO 442
#define IDR_FONT_DEPARTURE 420
#define IDR_FONT_TERMINESS 443
#define IDR_FONT_GOHUFONT 446
#define IDR_FONT_YESTERYEAR 490
#define IDR_FONT_ZCOOL_KUAILE 491
#define IDR_FONT_PROFONT 492
#define IDR_FONT_DADDYTIME 493

// 新增字体资源ID
#define IDR_FONT_ARBUTUS 447
#define IDR_FONT_BERKSHIRE 448
#define IDR_FONT_CAVEAT 449
#define IDR_FONT_CREEPSTER 450
#define IDR_FONT_DOTGOTHIC 451
#define IDR_FONT_DOTO 452
#define IDR_FONT_FOLDIT 454
#define IDR_FONT_FREDERICKA 455
#define IDR_FONT_FRIJOLE 456
#define IDR_FONT_GWENDOLYN 458
#define IDR_FONT_HANDJET 459
#define IDR_FONT_INKNUT 460
#define IDR_FONT_JACQUARD 461
#define IDR_FONT_JACQUARDA 462
#define IDR_FONT_KAVOON 463
#define IDR_FONT_KUMAR_ONE_OUTLINE 464
#define IDR_FONT_KUMAR_ONE 465
#define IDR_FONT_LAKKI_REDDY 466
#define IDR_FONT_LICORICE 467
#define IDR_FONT_MA_SHAN_ZHENG 468
#define IDR_FONT_MOIRAI_ONE 469
#define IDR_FONT_MYSTERY_QUEST 470
#define IDR_FONT_NOTO_NASTALIQ 471
#define IDR_FONT_PIEDRA 472
#define IDR_FONT_PIXELIFY 473
#define IDR_FONT_PRESS_START 474
#define IDR_FONT_RUBIK_BUBBLES 476
#define IDR_FONT_RUBIK_BURNED 477
#define IDR_FONT_RUBIK_GLITCH_POP 478
#define IDR_FONT_RUBIK_GLITCH 479
#define IDR_FONT_RUBIK_MARKER_HATCH 480
#define IDR_FONT_RUBIK_PUDDLES 481
#define IDR_FONT_RUBIK_VINYL 482
#define IDR_FONT_RUBIK_WET_PAINT 483
#define IDR_FONT_RUGE_BOOGIE 484
#define IDR_FONT_SEVILLANA 485
#define IDR_FONT_SILKSCREEN 486
#define IDR_FONT_STICK 487
#define IDR_FONT_UNDERDOG 488
#define IDR_FONT_WALLPOET 489

/* 主菜单功能项 */
#define CLOCK_IDM_OPEN_FILE 125
#define CLOCK_IDM_RECENT_FILE_1 126
#define CLOCK_IDM_RECENT_FILE_2 127
#define CLOCK_IDM_RECENT_FILE_3 128
#define CLOCK_IDM_BROWSE_FILE 129
#define CLOCK_IDM_ABOUT 130
#define CLOCK_IDM_VERSION 131
#define CLOCK_IDM_FEEDBACK 132
#define CLOCK_IDM_CHECK_UPDATE 133
#define CLOCK_IDM_UPDATE_GITHUB 134
#define CLOCK_IDM_UPDATE_123PAN 135
#define CLOCK_IDM_UPDATE_LANZOU 136
#define CLOCK_IDM_FEEDBACK_GITHUB 137
#define CLOCK_IDM_FEEDBACK_BILIBILI 138

/* 番茄钟功能 */
#define CLOCK_IDM_POMODORO 500
#define CLOCK_IDM_POMODORO_START 501
#define CLOCK_IDM_POMODORO_WORK 502
#define CLOCK_IDM_POMODORO_BREAK 503
#define CLOCK_IDM_POMODORO_LBREAK 504
#define CLOCK_IDM_POMODORO_RESET 505

/* 多语言支持 */
#define CLOCK_IDM_LANGUAGE_MENU 160
#define CLOCK_IDM_LANG_CHINESE 161
#define CLOCK_IDM_LANG_ENGLISH 162
#define CLOCK_IDM_LANG_CHINESE_TRAD 163
#define CLOCK_IDM_LANG_SPANISH 164
#define CLOCK_IDM_LANG_FRENCH 165
#define CLOCK_IDM_LANG_GERMAN 166
#define CLOCK_IDM_LANG_RUSSIAN 167
#define CLOCK_IDM_LANG_PORTUGUESE 168
#define CLOCK_IDM_LANG_JAPANESE 169
#define CLOCK_IDM_LANG_KOREAN 170

/* 计时器功能 */
#define CLOCK_IDM_COUNT_UP_START 171
#define CLOCK_IDM_COUNT_UP_RESET 172
#define CLOCK_IDM_COUNT_UP         153
#define CLOCK_IDM_COUNTDOWN_START_PAUSE 154
#define CLOCK_IDM_COUNTDOWN_RESET 155
#define CLOCK_IDC_TIMEOUT_BROWSE 140
#define CLOCK_IDC_MODIFY_TIME_OPTIONS 156
#define CLOCK_IDC_MODIFY_DEFAULT_TIME 157
#define CLOCK_IDC_SET_COUNTDOWN_TIME 173
#define CLOCK_IDC_START_NO_DISPLAY 174
#define CLOCK_IDC_START_COUNT_UP 175
#define CLOCK_IDC_AUTO_START 160
#define CLOCK_IDC_START_SHOW_TIME 176

/* 超时动作 */
#define CLOCK_IDM_TIMEOUT_ACTION 120
#define CLOCK_IDM_SHOW_MESSAGE 121
#define CLOCK_IDM_LOCK_SCREEN 122
#define CLOCK_IDM_SHUTDOWN 123
#define CLOCK_IDM_RESTART 124

/* 显示与视觉效果 */
#define BLUR_OPACITY 192
#define BLUR_TRANSITION_MS 200
#define CLOCK_IDM_SHOW_CURRENT_TIME 150
#define CLOCK_IDM_24HOUR_FORMAT    151
#define CLOCK_IDM_SHOW_SECONDS     152

/* 系统常量 */
#define CSIDL_STARTUP 0x0007
#define MAX_RECENT_FILES 5
#define MAX_TIME_OPTIONS 10
#define MIN_SCALE_FACTOR 0.5f
#define MAX_SCALE_FACTOR 100.0f
#define CLOCK_WM_TRAYICON (WM_USER + 2)

/* 关于对话框 */
#define IDD_ABOUT_DIALOG 1004
#define IDC_ABOUT_ICON 1005
#define IDC_VERSION_TEXT 1006
#define IDC_LIBS_TEXT 1007
#define IDC_AUTHOR_TEXT 1008
#define IDC_ABOUT_OK 1009
#define IDC_BUILD_DATE 1010
#define IDC_COPYRIGHT 1011

// 新增：关于对话框图标尺寸
#define ABOUT_ICON_SIZE 128

// 新增：关于对话框文本
#define IDC_ABOUT_TITLE L"Catime"
#define IDC_ABOUT_VERSION L"版本: "
#define IDC_COPYRIGHT_TEXT L"Copyright (C) 2025 By vladelaina"

