//版本
#define CATIME_VERSION "1.0.3.1"  

// 链接地址
#define UPDATE_URL_GITHUB    "https://github.com/vladelaina/Catime/releases"
#define UPDATE_URL_123PAN    "https://www.123684.com/s/ruESjv-2CZUA"
#define UPDATE_URL_LANZOU    "https://wwrx.lanzoup.com/b00hqiiskj"
#define FEEDBACK_URL        "https://www.bilibili.com/video/BV1ztFeeQEYP"
#define FEEDBACK_URL_GITHUB  "https://github.com/vladelaina/Catime/issues"
#define FEEDBACK_URL_BILIBILI "https://message.bilibili.com/#/whisper/mid1862395225"

// 系统按键
#define VK_MEDIA_PLAY_PAUSE 0xB3
#define VK_MEDIA_STOP 0xB2
#define KEYEVENTF_KEYUP 0x0002

// 基本对话框和控件
#define IDI_CATIME 101
#define CLOCK_ID_TRAY_APP_ICON 1001
#define CLOCK_IDD_DIALOG1 1002
#define CLOCK_IDD_COLOR_DIALOG 1003
#define CLOCK_IDC_EDIT 108
#define CLOCK_IDC_BUTTON_OK 109
#define CLOCK_IDC_CUSTOMIZE_LEFT 112
#define CLOCK_IDC_EDIT_MODE 113
#define CLOCK_IDC_MODIFY_OPTIONS 114

// 字体菜单ID
#define CLOCK_IDC_FONT_MENU 113
#define CLOCK_IDC_FONT_VICTORMONO 344
#define CLOCK_IDC_FONT_LIBERATION 338
#define CLOCK_IDC_FONT_ZEDMONO 345
#define CLOCK_IDC_FONT_RECMONO 342
#define CLOCK_IDC_FONT_IOSEVKA_TERM 334
#define CLOCK_IDC_FONT_ENVYCODE 321
#define CLOCK_IDC_FONT_DADDYTIME 319
#define CLOCK_IDC_FONT_PROFONT 307
#define CLOCK_IDC_FONT_HEAVYDATA 306
#define CLOCK_IDC_FONT_BIGBLUE 303
#define CLOCK_IDC_FONT_PROGGYCLEAN 313
#define CLOCK_IDC_FONT_DEPARTURE 320
#define CLOCK_IDC_FONT_TERMINESS 343
#define CLOCK_IDC_FONT_GOHUFONT 346

// 字体资源ID
#define IDR_FONT_VICTORMONO 444
#define IDR_FONT_LIBERATION 438
#define IDR_FONT_ZEDMONO 445
#define IDR_FONT_RECMONO 442
#define IDR_FONT_IOSEVKA_TERM 434
#define IDR_FONT_ENVYCODE 421
#define IDR_FONT_DADDYTIME 419
#define IDR_FONT_PROFONT 407
#define IDR_FONT_HEAVYDATA 406
#define IDR_FONT_BIGBLUE 403
#define IDR_FONT_PROGGYCLEAN 413
#define IDR_FONT_DEPARTURE 420
#define IDR_FONT_TERMINESS 443
#define IDR_FONT_GOHUFONT 446

// 菜单项
#define CLOCK_IDM_OPEN_FILE 125
#define CLOCK_IDM_RECENT_FILE_1 126
#define CLOCK_IDM_RECENT_FILE_2 127
#define CLOCK_IDM_RECENT_FILE_3 128
#define CLOCK_IDM_BROWSE_FILE 129
#define CLOCK_IDM_ABOUT 130
#define CLOCK_IDM_VERSION 131
#define CLOCK_IDM_FEEDBACK 132
#define CLOCK_IDM_CHECK_UPDATE 133
#define CLOCK_IDM_UPDATE_GITHUB 134
#define CLOCK_IDM_UPDATE_123PAN 135
#define CLOCK_IDM_UPDATE_LANZOU 136
#define CLOCK_IDM_FEEDBACK_GITHUB 137
#define CLOCK_IDM_FEEDBACK_BILIBILI 138

// 番茄时钟菜单项
#define CLOCK_IDM_POMODORO 500
#define CLOCK_IDM_POMODORO_START 501
#define CLOCK_IDM_POMODORO_WORK 502
#define CLOCK_IDM_POMODORO_BREAK 503
#define CLOCK_IDM_POMODORO_LBREAK 504
#define CLOCK_IDM_POMODORO_RESET 505

// 语言菜单项
#define CLOCK_IDM_LANGUAGE_MENU 160
#define CLOCK_IDM_LANG_CHINESE 161
#define CLOCK_IDM_LANG_ENGLISH 162
#define CLOCK_IDM_LANG_CHINESE_TRAD 163
#define CLOCK_IDM_LANG_SPANISH 164
#define CLOCK_IDM_LANG_FRENCH 165
#define CLOCK_IDM_LANG_GERMAN 166
#define CLOCK_IDM_LANG_RUSSIAN 167
#define CLOCK_IDM_LANG_PORTUGUESE 168
#define CLOCK_IDM_LANG_JAPANESE 169
#define CLOCK_IDM_LANG_KOREAN 170

// 计时器控件
#define CLOCK_IDM_COUNT_UP_START 171
#define CLOCK_IDM_COUNT_UP_RESET 172
#define CLOCK_IDC_TIMEOUT_BROWSE 140
#define CLOCK_IDC_MODIFY_TIME_OPTIONS 156
#define CLOCK_IDC_MODIFY_DEFAULT_TIME 157
#define CLOCK_IDC_SET_COUNTDOWN_TIME 173
#define CLOCK_IDC_START_NO_DISPLAY 174
#define CLOCK_IDC_START_COUNT_UP 175
#define CLOCK_IDC_AUTO_START 160
#define CLOCK_IDC_START_SHOW_TIME 176

// 超时动作
#define CLOCK_IDM_TIMEOUT_ACTION 120
#define CLOCK_IDM_SHOW_MESSAGE 121
#define CLOCK_IDM_LOCK_SCREEN 122
#define CLOCK_IDM_SHUTDOWN 123
#define CLOCK_IDM_RESTART 124

// 颜色和视觉设置
#define CLOCK_IDC_COLOR_VALUE 1301
#define CLOCK_IDC_COLOR_PANEL 1302
#define BLUR_OPACITY 192
#define BLUR_TRANSITION_MS 200

// 其他常量
#define MAX_TIME_OPTIONS 10
