/**
 * @file config_defaults.c
 * @brief Configuration metadata and default-value lookup.
 */

#include "config_defaults_internal.h"

/* Helper macros for metadata table */
#define CFG_OFFSET(field) offsetof(ConfigSnapshot, field)
#define CFG_SIZE(field)   sizeof(((ConfigSnapshot*)0)->field)
#define CFG_NO_OFFSET     SIZE_MAX
#define CFG_NO_SIZE       0

/* ============================================================================
 * Configuration metadata table
 * ============================================================================ */

const ConfigItemMeta CONFIG_METADATA[] = {
    /* General settings */
    /* CONFIG_VERSION and FIRST_RUN are not mapped to ConfigSnapshot - handled separately */
    {INI_SECTION_GENERAL, "CONFIG_VERSION", CATIME_VERSION, CONFIG_TYPE_STRING, CFG_NO_OFFSET, CFG_NO_SIZE},
    {INI_SECTION_GENERAL, "LANGUAGE", "English", CONFIG_TYPE_STRING, CFG_OFFSET(language), CFG_SIZE(language)},
    {INI_SECTION_GENERAL, "SHORTCUT_CHECK_DONE", "FALSE", CONFIG_TYPE_BOOL, CFG_NO_OFFSET, CFG_NO_SIZE},
    {INI_SECTION_GENERAL, "FIRST_RUN", "TRUE", CONFIG_TYPE_BOOL, CFG_NO_OFFSET, CFG_NO_SIZE},
    {INI_SECTION_GENERAL, "AUTO_START_PREFERENCE", "DEFAULT", CONFIG_TYPE_ENUM, CFG_NO_OFFSET, CFG_NO_SIZE},
    {INI_SECTION_GENERAL, "FONT_LICENSE_ACCEPTED", "FALSE", CONFIG_TYPE_BOOL, CFG_OFFSET(fontLicenseAccepted), CFG_NO_SIZE},
    {INI_SECTION_GENERAL, "FONT_LICENSE_VERSION_ACCEPTED", "", CONFIG_TYPE_STRING, CFG_OFFSET(fontLicenseVersion), CFG_SIZE(fontLicenseVersion)},

    /* Display settings */
    {INI_SECTION_DISPLAY, "CLOCK_TEXT_COLOR", DEFAULT_TEXT_COLOR, CONFIG_TYPE_STRING, CFG_OFFSET(textColor), CFG_SIZE(textColor)},
    {INI_SECTION_DISPLAY, "CLOCK_BASE_FONT_SIZE", "20", CONFIG_TYPE_INT, CFG_OFFSET(baseFontSize), CFG_NO_SIZE},
    {INI_SECTION_DISPLAY, "FONT_FILE_NAME", FONTS_PATH_PREFIX DEFAULT_FONT_NAME, CONFIG_TYPE_CUSTOM, CFG_OFFSET(fontFileName), CFG_SIZE(fontFileName)},
    {INI_SECTION_DISPLAY, "CLOCK_WINDOW_POS_X", "-2", CONFIG_TYPE_INT, CFG_OFFSET(windowPosX), CFG_NO_SIZE},
    {INI_SECTION_DISPLAY, "CLOCK_WINDOW_POS_Y", "-1", CONFIG_TYPE_INT, CFG_OFFSET(windowPosY), CFG_NO_SIZE},
    {INI_SECTION_DISPLAY, WINDOW_POSITION_MANUAL_KEY, "FALSE", CONFIG_TYPE_BOOL, CFG_NO_OFFSET, CFG_NO_SIZE},
    {INI_SECTION_DISPLAY, WINDOW_MONITOR_ID_KEY, "", CONFIG_TYPE_STRING, CFG_NO_OFFSET, CFG_NO_SIZE},
    {INI_SECTION_DISPLAY, WINDOW_MONITOR_OFFSET_X_KEY, "0", CONFIG_TYPE_INT, CFG_NO_OFFSET, CFG_NO_SIZE},
    {INI_SECTION_DISPLAY, WINDOW_MONITOR_OFFSET_Y_KEY, "0", CONFIG_TYPE_INT, CFG_NO_OFFSET, CFG_NO_SIZE},
    {INI_SECTION_DISPLAY, WINDOW_TASKBAR_ANCHORED_KEY, "FALSE", CONFIG_TYPE_BOOL, CFG_NO_OFFSET, CFG_NO_SIZE},
    {INI_SECTION_DISPLAY, WINDOW_TASKBAR_AXIS_RATIO_KEY, "0", CONFIG_TYPE_INT, CFG_NO_OFFSET, CFG_NO_SIZE},
    {INI_SECTION_DISPLAY, WINDOW_TASKBAR_CROSS_OFFSET_KEY, "0", CONFIG_TYPE_INT, CFG_NO_OFFSET, CFG_NO_SIZE},
    {INI_SECTION_DISPLAY, "WINDOW_SCALE", DEFAULT_WINDOW_SCALE, CONFIG_TYPE_FLOAT, CFG_OFFSET(windowScale), CFG_NO_SIZE},
    {INI_SECTION_DISPLAY, "PLUGIN_SCALE", DEFAULT_PLUGIN_SCALE, CONFIG_TYPE_FLOAT, CFG_OFFSET(pluginScale), CFG_NO_SIZE},
    {INI_SECTION_DISPLAY, "WINDOW_TOPMOST", "TRUE", CONFIG_TYPE_BOOL, CFG_OFFSET(windowTopmost), CFG_NO_SIZE},
    {INI_SECTION_DISPLAY, "WINDOW_OPACITY", "100", CONFIG_TYPE_INT, CFG_OFFSET(windowOpacity), CFG_NO_SIZE},
    {INI_SECTION_DISPLAY, "MOVE_STEP_SMALL", "10", CONFIG_TYPE_INT, CFG_OFFSET(moveStepSmall), CFG_NO_SIZE},
    {INI_SECTION_DISPLAY, "MOVE_STEP_LARGE", "50", CONFIG_TYPE_INT, CFG_OFFSET(moveStepLarge), CFG_NO_SIZE},
    {INI_SECTION_DISPLAY, "OPACITY_STEP_NORMAL", "1", CONFIG_TYPE_INT, CFG_OFFSET(opacityStepNormal), CFG_NO_SIZE},
    {INI_SECTION_DISPLAY, "OPACITY_STEP_FAST", "5", CONFIG_TYPE_INT, CFG_OFFSET(opacityStepFast), CFG_NO_SIZE},
    {INI_SECTION_DISPLAY, "SCALE_STEP_NORMAL", "10", CONFIG_TYPE_INT, CFG_OFFSET(scaleStepNormal), CFG_NO_SIZE},
    {INI_SECTION_DISPLAY, "SCALE_STEP_FAST", "15", CONFIG_TYPE_INT, CFG_OFFSET(scaleStepFast), CFG_NO_SIZE},
    {INI_SECTION_DISPLAY, "TEXT_EFFECT", "NONE", CONFIG_TYPE_ENUM, CFG_OFFSET(textEffect), CFG_NO_SIZE},

    /* Timer settings */
    {INI_SECTION_TIMER, "CLOCK_DEFAULT_START_TIME", "1500", CONFIG_TYPE_INT, CFG_OFFSET(defaultStartTime), CFG_NO_SIZE},
    {INI_SECTION_TIMER, "CLOCK_USE_24HOUR", "TRUE", CONFIG_TYPE_BOOL, CFG_OFFSET(use24Hour), CFG_NO_SIZE},
    {INI_SECTION_TIMER, "CLOCK_SHOW_SECONDS", "FALSE", CONFIG_TYPE_BOOL, CFG_OFFSET(showSeconds), CFG_NO_SIZE},
    {INI_SECTION_TIMER, "CLOCK_TIME_FORMAT", "DEFAULT", CONFIG_TYPE_ENUM, CFG_OFFSET(timeFormat), CFG_NO_SIZE},
    {INI_SECTION_TIMER, "CLOCK_SHOW_MILLISECONDS", "FALSE", CONFIG_TYPE_BOOL, CFG_OFFSET(showMilliseconds), CFG_NO_SIZE},
    {INI_SECTION_TIMER, "CLOCK_TIME_OPTIONS", DEFAULT_TIME_OPTIONS_INI, CONFIG_TYPE_CUSTOM, CFG_NO_OFFSET, CFG_NO_SIZE},
    {INI_SECTION_TIMER, "CLOCK_TIMEOUT_TEXT", "0", CONFIG_TYPE_STRING, CFG_OFFSET(timeoutText), CFG_SIZE(timeoutText)},
    {INI_SECTION_TIMER, "CLOCK_TIMEOUT_ACTION", "MESSAGE", CONFIG_TYPE_ENUM, CFG_OFFSET(timeoutAction), CFG_NO_SIZE},
    {INI_SECTION_TIMER, "CLOCK_TIMEOUT_FILE", "", CONFIG_TYPE_STRING, CFG_OFFSET(timeoutFilePath), CFG_SIZE(timeoutFilePath)},
    {INI_SECTION_TIMER, "CLOCK_TIMEOUT_WEBSITE", "", CONFIG_TYPE_CUSTOM, CFG_NO_OFFSET, CFG_NO_SIZE},
    {INI_SECTION_TIMER, "STARTUP_MODE", "SHOW_TIME", CONFIG_TYPE_STRING, CFG_OFFSET(startupMode), CFG_SIZE(startupMode)},

    /* Pomodoro settings */
    {INI_SECTION_POMODORO, "POMODORO_TIME_OPTIONS", DEFAULT_POMODORO_OPTIONS_INI, CONFIG_TYPE_CUSTOM, CFG_NO_OFFSET, CFG_NO_SIZE},
    {INI_SECTION_POMODORO, "POMODORO_LOOP_COUNT", "1", CONFIG_TYPE_INT, CFG_OFFSET(pomodoroLoopCount), CFG_NO_SIZE},

    /* Notification settings */
    {INI_SECTION_NOTIFICATION, "CLOCK_TIMEOUT_MESSAGE_TEXT", DEFAULT_TIMEOUT_MESSAGE, CONFIG_TYPE_STRING, CFG_OFFSET(timeoutMessage), CFG_SIZE(timeoutMessage)},
    {INI_SECTION_NOTIFICATION, "NOTIFICATION_TIMEOUT_MS", "3000", CONFIG_TYPE_INT, CFG_OFFSET(notificationTimeoutMs), CFG_NO_SIZE},
    {INI_SECTION_NOTIFICATION, "NOTIFICATION_MAX_OPACITY", "95", CONFIG_TYPE_INT, CFG_OFFSET(notificationMaxOpacity), CFG_NO_SIZE},
    {INI_SECTION_NOTIFICATION, "NOTIFICATION_CORNER_RADIUS", "12", CONFIG_TYPE_INT, CFG_OFFSET(notificationCornerRadius), CFG_NO_SIZE},
    {INI_SECTION_NOTIFICATION, "NOTIFICATION_FONT_SIZE", "100", CONFIG_TYPE_INT, CFG_OFFSET(notificationFontSize), CFG_NO_SIZE},
    {INI_SECTION_NOTIFICATION, "NOTIFICATION_TYPE", "CATIME", CONFIG_TYPE_ENUM, CFG_OFFSET(notificationType), CFG_NO_SIZE},
    {INI_SECTION_NOTIFICATION, "NOTIFICATION_SOUND_FILE", "", CONFIG_TYPE_STRING, CFG_OFFSET(notificationSoundFile), CFG_SIZE(notificationSoundFile)},
    {INI_SECTION_NOTIFICATION, "NOTIFICATION_SOUND_VOLUME", "100", CONFIG_TYPE_INT, CFG_OFFSET(notificationSoundVolume), CFG_NO_SIZE},
    {INI_SECTION_NOTIFICATION, "NOTIFICATION_DISABLED", "FALSE", CONFIG_TYPE_BOOL, CFG_OFFSET(notificationDisabled), CFG_NO_SIZE},
    {INI_SECTION_NOTIFICATION, "NOTIFICATION_WINDOW_X", "-1", CONFIG_TYPE_INT, CFG_OFFSET(notificationWindowX), CFG_NO_SIZE},
    {INI_SECTION_NOTIFICATION, "NOTIFICATION_WINDOW_Y", "-1", CONFIG_TYPE_INT, CFG_OFFSET(notificationWindowY), CFG_NO_SIZE},
    {INI_SECTION_NOTIFICATION, "NOTIFICATION_WINDOW_WIDTH", "0", CONFIG_TYPE_INT, CFG_OFFSET(notificationWindowWidth), CFG_NO_SIZE},
    {INI_SECTION_NOTIFICATION, "NOTIFICATION_WINDOW_HEIGHT", "0", CONFIG_TYPE_INT, CFG_OFFSET(notificationWindowHeight), CFG_NO_SIZE},

    /* Animation settings - not mapped to ConfigSnapshot, handled by tray_animation_core */
    {"Animation", "ANIMATION_PATH", "__logo__", CONFIG_TYPE_STRING, CFG_NO_OFFSET, CFG_NO_SIZE},
    {"Animation", "ANIMATION_SPEED_METRIC", "MEMORY", CONFIG_TYPE_ENUM, CFG_NO_OFFSET, CFG_NO_SIZE},
    {"Animation", "ANIMATION_FIXED_SPEED_PERCENT", "200", CONFIG_TYPE_FLOAT, CFG_NO_OFFSET, CFG_NO_SIZE},
    {"Animation", "ANIMATION_SPEED_DEFAULT", "100", CONFIG_TYPE_INT, CFG_NO_OFFSET, CFG_NO_SIZE},
    {"Animation", "ANIMATION_SPEED_MAP_10", "140", CONFIG_TYPE_STRING, CFG_NO_OFFSET, CFG_NO_SIZE},
    {"Animation", "ANIMATION_SPEED_MAP_20", "180", CONFIG_TYPE_STRING, CFG_NO_OFFSET, CFG_NO_SIZE},
    {"Animation", "ANIMATION_SPEED_MAP_30", "220", CONFIG_TYPE_STRING, CFG_NO_OFFSET, CFG_NO_SIZE},
    {"Animation", "ANIMATION_SPEED_MAP_40", "260", CONFIG_TYPE_STRING, CFG_NO_OFFSET, CFG_NO_SIZE},
    {"Animation", "ANIMATION_SPEED_MAP_50", "300", CONFIG_TYPE_STRING, CFG_NO_OFFSET, CFG_NO_SIZE},
    {"Animation", "ANIMATION_SPEED_MAP_60", "340", CONFIG_TYPE_STRING, CFG_NO_OFFSET, CFG_NO_SIZE},
    {"Animation", "ANIMATION_SPEED_MAP_70", "380", CONFIG_TYPE_STRING, CFG_NO_OFFSET, CFG_NO_SIZE},
    {"Animation", "ANIMATION_SPEED_MAP_80", "420", CONFIG_TYPE_STRING, CFG_NO_OFFSET, CFG_NO_SIZE},
    {"Animation", "ANIMATION_SPEED_MAP_90", "460", CONFIG_TYPE_STRING, CFG_NO_OFFSET, CFG_NO_SIZE},
    {"Animation", "ANIMATION_SPEED_MAP_100", "500", CONFIG_TYPE_STRING, CFG_NO_OFFSET, CFG_NO_SIZE},
    {"Animation", "PERCENT_ICON_TEXT_COLOR", "auto", CONFIG_TYPE_STRING, CFG_NO_OFFSET, CFG_NO_SIZE},
    {"Animation", "PERCENT_ICON_BG_COLOR", "transparent", CONFIG_TYPE_STRING, CFG_NO_OFFSET, CFG_NO_SIZE},
    {"Animation", "ANIMATION_FOLDER_INTERVAL_MS", "150", CONFIG_TYPE_INT, CFG_NO_OFFSET, CFG_NO_SIZE},
    {"Animation", "ANIMATION_MIN_INTERVAL_MS", "0", CONFIG_TYPE_INT, CFG_NO_OFFSET, CFG_NO_SIZE},
    {"Animation", "TASKBAR_MONITOR_ENABLED", "FALSE", CONFIG_TYPE_BOOL, CFG_OFFSET(taskbarMonitorEnabled), CFG_NO_SIZE},
    {"Animation", "TASKBAR_MONITOR_CPU_MEMORY", "TRUE", CONFIG_TYPE_BOOL, CFG_OFFSET(taskbarMonitorCpuMemory), CFG_NO_SIZE},
    {"Animation", "TASKBAR_MONITOR_NETWORK", "TRUE", CONFIG_TYPE_BOOL, CFG_OFFSET(taskbarMonitorNetwork), CFG_NO_SIZE},

    /* Hotkeys */
    {INI_SECTION_HOTKEYS, "HOTKEY_SHOW_TIME", "None", CONFIG_TYPE_HOTKEY, CFG_OFFSET(hotkeyShowTime), CFG_NO_SIZE},
    {INI_SECTION_HOTKEYS, "HOTKEY_COUNT_UP", "None", CONFIG_TYPE_HOTKEY, CFG_OFFSET(hotkeyCountUp), CFG_NO_SIZE},
    {INI_SECTION_HOTKEYS, "HOTKEY_COUNTDOWN", "None", CONFIG_TYPE_HOTKEY, CFG_OFFSET(hotkeyCountdown), CFG_NO_SIZE},
    {INI_SECTION_HOTKEYS, "HOTKEY_QUICK_COUNTDOWN1", "None", CONFIG_TYPE_HOTKEY, CFG_OFFSET(hotkeyQuickCountdown1), CFG_NO_SIZE},
    {INI_SECTION_HOTKEYS, "HOTKEY_QUICK_COUNTDOWN2", "None", CONFIG_TYPE_HOTKEY, CFG_OFFSET(hotkeyQuickCountdown2), CFG_NO_SIZE},
    {INI_SECTION_HOTKEYS, "HOTKEY_QUICK_COUNTDOWN3", "None", CONFIG_TYPE_HOTKEY, CFG_OFFSET(hotkeyQuickCountdown3), CFG_NO_SIZE},
    {INI_SECTION_HOTKEYS, "HOTKEY_POMODORO", "None", CONFIG_TYPE_HOTKEY, CFG_OFFSET(hotkeyPomodoro), CFG_NO_SIZE},
    {INI_SECTION_HOTKEYS, "HOTKEY_TOGGLE_VISIBILITY", "None", CONFIG_TYPE_HOTKEY, CFG_OFFSET(hotkeyToggleVisibility), CFG_NO_SIZE},
    {INI_SECTION_HOTKEYS, "HOTKEY_EDIT_MODE", "None", CONFIG_TYPE_HOTKEY, CFG_OFFSET(hotkeyEditMode), CFG_NO_SIZE},
    {INI_SECTION_HOTKEYS, "HOTKEY_PAUSE_RESUME", "None", CONFIG_TYPE_HOTKEY, CFG_OFFSET(hotkeyPauseResume), CFG_NO_SIZE},
    {INI_SECTION_HOTKEYS, "HOTKEY_RESTART_TIMER", "None", CONFIG_TYPE_HOTKEY, CFG_OFFSET(hotkeyRestartTimer), CFG_NO_SIZE},
    {INI_SECTION_HOTKEYS, "HOTKEY_CUSTOM_COUNTDOWN", "None", CONFIG_TYPE_HOTKEY, CFG_OFFSET(hotkeyCustomCountdown), CFG_NO_SIZE},
    {INI_SECTION_HOTKEYS, "HOTKEY_TOGGLE_MILLISECONDS", "None", CONFIG_TYPE_HOTKEY, CFG_OFFSET(hotkeyToggleMilliseconds), CFG_NO_SIZE},
    {INI_SECTION_HOTKEYS, "HOTKEY_TOPMOST", "None", CONFIG_TYPE_HOTKEY, CFG_OFFSET(hotkeyTopmost), CFG_NO_SIZE},

    /* Colors */
    {INI_SECTION_COLORS, "COLOR_OPTIONS", DEFAULT_COLOR_OPTIONS_INI, CONFIG_TYPE_STRING, CFG_OFFSET(colorOptions), CFG_SIZE(colorOptions)},

    /* Recent files - handled separately via custom logic */
};

const int CONFIG_METADATA_COUNT = sizeof(CONFIG_METADATA) / sizeof(CONFIG_METADATA[0]);

/* ============================================================================
 * Public API Implementation
 * ============================================================================ */

const ConfigItemMeta* GetConfigMetadata(int* count) {
    if (count) {
        *count = CONFIG_METADATA_COUNT;
    }
    return CONFIG_METADATA;
}

const char* GetDefaultValue(const char* section, const char* key) {
    if (!section || !key) return NULL;

    for (int i = 0; i < CONFIG_METADATA_COUNT; i++) {
        if (strcmp(CONFIG_METADATA[i].section, section) == 0 &&
            strcmp(CONFIG_METADATA[i].key, key) == 0) {
            return CONFIG_METADATA[i].defaultValue;
        }
    }

    return NULL;
}
