#ifndef CLOCK_TRAY_MENU_H
#define CLOCK_TRAY_MENU_H

#include <windows.h>

// 托盘菜单项ID
#define CLOCK_IDM_SHOW_CURRENT_TIME 301
#define CLOCK_IDM_24HOUR_FORMAT 302
#define CLOCK_IDM_SHOW_SECONDS 303
#define CLOCK_IDM_COUNT_UP_START 304
#define CLOCK_IDM_COUNT_UP_RESET 305
#define CLOCK_IDM_COUNTDOWN_START_PAUSE 306
#define CLOCK_IDM_COUNTDOWN_RESET 307
#define CLOCK_IDC_EDIT_MODE 308
#define CLOCK_IDM_SHOW_MESSAGE 309
#define CLOCK_IDM_LOCK_SCREEN 310
#define CLOCK_IDM_SHUTDOWN 311
#define CLOCK_IDM_RESTART 312
#define CLOCK_IDM_BROWSE_FILE 313
#define CLOCK_IDM_RECENT_FILE_1 314
#define CLOCK_IDC_MODIFY_TIME_OPTIONS 315
#define CLOCK_IDC_SET_COUNTDOWN_TIME 316
#define CLOCK_IDC_START_COUNT_UP 317
#define CLOCK_IDC_START_SHOW_TIME 318
#define CLOCK_IDC_START_NO_DISPLAY 319
#define CLOCK_IDC_AUTO_START 320
#define CLOCK_IDC_COLOR_VALUE 321
#define CLOCK_IDC_COLOR_PANEL 322
#define CLOCK_IDM_FEEDBACK_GITHUB 323
#define CLOCK_IDM_FEEDBACK_BILIBILI 324
#define CLOCK_IDM_LANG_CHINESE 325
#define CLOCK_IDM_LANG_CHINESE_TRAD 326
#define CLOCK_IDM_LANG_ENGLISH 327
#define CLOCK_IDM_LANG_SPANISH 328
#define CLOCK_IDM_LANG_FRENCH 329
#define CLOCK_IDM_LANG_GERMAN 330
#define CLOCK_IDM_LANG_RUSSIAN 331
#define CLOCK_IDM_LANG_KOREAN 332
#define CLOCK_IDM_UPDATE_GITHUB 333
#define CLOCK_IDM_UPDATE_123PAN 334
#define CLOCK_IDM_UPDATE_LANZOU 335

// 显示托盘菜单
void ShowContextMenu(HWND hwnd);

// 显示颜色菜单
void ShowColorMenu(HWND hwnd);

#endif // CLOCK_TRAY_MENU_H