#ifndef CLOCK_TRAY_MENU_H
#define CLOCK_TRAY_MENU_H

#include <windows.h>

#define CLOCK_IDM_SHOW_CURRENT_TIME 150
#define CLOCK_IDM_24HOUR_FORMAT 151
#define CLOCK_IDM_SHOW_SECONDS 152

#define CLOCK_IDM_TIMER_MANAGEMENT 159
#define CLOCK_IDM_TIMER_PAUSE_RESUME 158
#define CLOCK_IDM_TIMER_RESTART 177
#define CLOCK_IDM_COUNT_UP_START 171
#define CLOCK_IDM_COUNT_UP_RESET 172
#define CLOCK_IDM_COUNTDOWN_START_PAUSE 154
#define CLOCK_IDM_COUNTDOWN_RESET 155

#define CLOCK_IDC_EDIT_MODE 113

#define CLOCK_IDM_SHOW_MESSAGE 121
#define CLOCK_IDM_LOCK_SCREEN 122
#define CLOCK_IDM_SHUTDOWN 123
#define CLOCK_IDM_RESTART 124
#define CLOCK_IDM_SLEEP 125
#define CLOCK_IDM_BROWSE_FILE 131
#define CLOCK_IDM_RECENT_FILE_1 126
#define CLOCK_IDM_TIMEOUT_SHOW_TIME 135
#define CLOCK_IDM_TIMEOUT_COUNT_UP 136

#define CLOCK_IDC_MODIFY_TIME_OPTIONS 156

#define CLOCK_IDC_SET_COUNTDOWN_TIME 173
#define CLOCK_IDC_START_COUNT_UP 175
#define CLOCK_IDC_START_SHOW_TIME 176
#define CLOCK_IDC_START_NO_DISPLAY 174
#define CLOCK_IDC_AUTO_START 160

#define CLOCK_IDM_NOTIFICATION_SETTINGS 193
#define CLOCK_IDM_NOTIFICATION_CONTENT 191
#define CLOCK_IDM_NOTIFICATION_DISPLAY 192

#define CLOCK_IDM_POMODORO_START 181
#define CLOCK_IDM_POMODORO_WORK 182
#define CLOCK_IDM_POMODORO_BREAK 183
#define CLOCK_IDM_POMODORO_LBREAK 184
#define CLOCK_IDM_POMODORO_LOOP_COUNT 185
#define CLOCK_IDM_POMODORO_RESET 186

#define CLOCK_IDC_COLOR_VALUE 1301
#define CLOCK_IDC_COLOR_PANEL 1302

#define CLOCK_IDM_LANG_CHINESE 161
#define CLOCK_IDM_LANG_CHINESE_TRAD 163
#define CLOCK_IDM_LANG_ENGLISH 162
#define CLOCK_IDM_LANG_SPANISH 164
#define CLOCK_IDM_LANG_FRENCH 165
#define CLOCK_IDM_LANG_GERMAN 166
#define CLOCK_IDM_LANG_RUSSIAN 167
#define CLOCK_IDM_LANG_KOREAN 170

void ShowContextMenu(HWND hwnd);

void ShowColorMenu(HWND hwnd);

#endif