#ifndef SHORTCUT_POLICY_H
#define SHORTCUT_POLICY_H

#include <stdbool.h>

/* Returns true only for the legacy direct-executable shortcut generated by
 * Catime Store builds, regardless of the drive containing WindowsApps. */
bool ShortcutPolicy_IsLegacyPackagedTarget(const char* targetPath,
                                            const char* packageName,
                                            const char* executableName);

#endif
