#ifndef DIALOG_REGISTRY_H
#define DIALOG_REGISTRY_H

#include <windows.h>

typedef enum {
    DIALOG_INSTANCE_ERROR,
    DIALOG_INSTANCE_MESSAGE_INFO,
    DIALOG_INSTANCE_MESSAGE_WARNING,
    DIALOG_INSTANCE_MESSAGE_ERROR,
    DIALOG_INSTANCE_INPUT,
    DIALOG_INSTANCE_ABOUT,
    DIALOG_INSTANCE_POMODORO_LOOP,
    DIALOG_INSTANCE_POMODORO_COMBO,
    DIALOG_INSTANCE_WEBSITE,
    DIALOG_INSTANCE_NOTIFICATION_MSG,
    DIALOG_INSTANCE_NOTIFICATION_DISP,
    DIALOG_INSTANCE_NOTIFICATION_FULL,
    DIALOG_INSTANCE_SHORTCUT,
    DIALOG_INSTANCE_STARTUP,
    DIALOG_INSTANCE_POMODORO_TIME,
    DIALOG_INSTANCE_INPUT_BOX,
    DIALOG_INSTANCE_COLOR,
    DIALOG_INSTANCE_COLOR_PICKER,
    DIALOG_INSTANCE_HOTKEY,
    DIALOG_INSTANCE_UPDATE,
    DIALOG_INSTANCE_NO_UPDATE,
    DIALOG_INSTANCE_EXIT_MSG,
    DIALOG_INSTANCE_PLUGIN_SECURITY,
    DIALOG_INSTANCE_FONT_LICENSE,
    DIALOG_INSTANCE_FONT_PICKER,
    DIALOG_INSTANCE_UPDATE_ERROR,
    DIALOG_INSTANCE_CLI_HELP,
    DIALOG_INSTANCE_CUSTOM_TEXT_DISPLAY,
    DIALOG_INSTANCE_COUNT
} DialogInstanceType;

void Dialog_RegisterInstance(DialogInstanceType type, HWND hwnd);
void Dialog_InitializeInstance(DialogInstanceType type, HWND hwnd);
void Dialog_UnregisterInstance(DialogInstanceType type);
void Dialog_UnregisterInstanceForWindow(DialogInstanceType type, HWND hwnd);
HWND Dialog_GetInstance(DialogInstanceType type);
BOOL Dialog_IsOpen(DialogInstanceType type);
void Dialog_RefreshOpenThemes(void);
BOOL Dialog_ProcessModelessMessage(MSG* msg);

#endif
